[package]
name = "ophelia"
version = "0.3.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"
license = "MIT"
description = "ophelia crypto collection"

[dependencies]
anyhow = "1.0"
bytes = "0.5"
ophelia-hasher = { path = "../ophelia-hasher", version = "0.2" }
rand_core = "0.5"
