[workspace]

members = [
  "ophelia",
  "ophelia-secp256k1",
  "ophelia-ed25519",
  "ophelia-quickcheck-types",
  "ophelia-derive",
  "ophelia-sm2",
  "ophelia-hasher",
  "ophelia-hasher-keccak256",
  "ophelia-hasher-blake2b",
  "ophelia-hasher-sm3",
]
