[workspace]

members = [
  "ophelia",
  "ophelia-bls-amcl",
  "ophelia-ed25519",
  "ophelia-secp256k1",
  "ophelia-derive",
  "ophelia-quickcheck",
  "ophelia-hasher",
  "ophelia-hasher-keccak256",
  "ophelia-hasher-blake2b",
]
