[package]
name = "ophelia-hasher"
version = "0.1.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"
license = "MIT"
description = "ophelia hasher trait"

[dependencies]
thiserror = "1.0.9"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
